version: "3"

services:
  api:
    container_name: node-api-icecream
    restart: always
    build: .
    ports:
      - "4000:5000"
    depends_on:
      - mongodb
  mongodb:
    container_name: mymongodb
    image: mongo
    ports:
      - "27017:27017"
    logging:
      driver: none